# Generated by Django 5.2 on 2025-04-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['user', 'menu_type'], 'verbose_name': 'Подписки'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='recipe_app.menutype', verbose_name='Тип меню'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='recipe_app.userpage', verbose_name='Пользователь'),
        ),
    ]
