# Generated by Django 5.2 on 2025-04-27 23:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpage',
            options={'ordering': ['username'], 'verbose_name': 'Страницы клиентов'},
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='menu_type',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='dessert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dessert_menus', to='recipe_app.recipe'),
        ),
        migrations.AddField(
            model_name='userpage',
            name='menu_types',
            field=models.ManyToManyField(blank=True, to='recipe_app.menutype', verbose_name='Диеты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('dessert', 'Десерт')], default='breakfast', max_length=20, verbose_name='Прием пищи'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимальный срок - 1 месяц'), django.core.validators.MaxValueValidator(12, message='Максимальный срок - 12 месяцев (1 год)')], verbose_name='Количество месяцев')),
                ('persons', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимум - 1 человек'), django.core.validators.MaxValueValidator(5, message='Максимум - 5 человек')], verbose_name='Количество персон')),
                ('breakfasts', models.BooleanField(default=False, verbose_name='Завтраки')),
                ('lunches', models.BooleanField(default=True, verbose_name='Обеды')),
                ('dinners', models.BooleanField(default=False, verbose_name='Ужины')),
                ('desserts', models.BooleanField(default=False, verbose_name='Десерты')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='recipe_app.userpage', verbose_name='Пользователь')),
            ],
        ),
    ]
