# Generated by Django 5.2 on 2025-04-28 00:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_alter_userpage_options_remove_userpage_menu_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='breakfasts',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='desserts',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='dinners',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='lunches',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='today_menu',
        ),
        migrations.AddField(
            model_name='dailymenu',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='daily_menu', to='recipe_app.userpage', verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe_app.menutype', verbose_name='Тип меню'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Базовая стоимость подписки, руб'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='meal_plan',
            field=models.CharField(choices=[('breakfasts', 'Завтраки'), ('dinners', 'Обеды'), ('suppers', 'Ужины'), ('desserts', 'Десерты')], default='breakfasts', max_length=20, verbose_name='Тип питания'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость, руб.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='persons',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Минимум - 1 персона'), django.core.validators.MaxValueValidator(5, message='Максимум - 5 персон')], verbose_name='Количество персон'),
        ),
    ]
