# Generated by Django 5.2 on 2025-04-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(related_name='users', to='recipe_app.allergy', verbose_name='Аллергии'),
        ),
    ]
