# Generated by Django 5.2 on 2025-04-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_food_tag_remove_ingredient_price_range_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_Tag',
            new_name='FoodTag',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userrecipechoice',
            name='swap_count',
        ),
        migrations.AddField(
            model_name='recipe',
            name='sequence',
            field=models.TextField(blank=True, verbose_name='Пошаговая инструкция'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipe_app.foodtag', verbose_name='Теги ингредиента'),
        ),
    ]
