# Generated by Django 5.2 on 2025-04-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_rename_food_tag_foodtag_remove_ingredient_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='recipe_app.foodtag', verbose_name='Теги блюда'),
        ),
    ]
