# Generated by Django 5.2 on 2025-04-26 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allergies',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Юзеры'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='diet_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(default=False)),
                ('allergies', models.ManyToManyField(blank=True, related_name='userpages', to='recipe_app.foodtag', verbose_name='Аллергии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
    ]
