# Generated by Django 5.2 on 2025-04-26 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_remove_user_allergies_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpage',
            options={'ordering': ['first_name', 'user'], 'verbose_name': 'Страницы клиентов'},
        ),
        migrations.AddField(
            model_name='userpage',
            name='first_name',
            field=models.CharField(blank=True, default='Имя', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='userpage',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Связанный аккаунт'),
        ),
    ]
