# Generated by Django 5.2 on 2025-04-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_remove_subscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='meal_plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Завтраки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dessert',
            field=models.BooleanField(default=False, verbose_name='Десерты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Ужины'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Обеды'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='promocode',
            field=models.CharField(blank=True, max_length=255, verbose_name='Промокод'),
        ),
    ]
