# Generated by Django 5.2 on 2025-04-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='foodtags', to='recipe_app.foodtag', verbose_name='Теги блюда'),
        ),
    ]
