# Generated by Django 5.2 on 2025-04-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_remove_subscription_meal_plan_subscription_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='promocode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Промокод'),
        ),
    ]
