# Generated by Django 5.2 on 2025-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_alter_userpage_options_userpage_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./avatars/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='./recipes/', verbose_name='Изображение'),
        ),
    ]
