# Generated by Django 5.2 on 2025-04-26 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_userpage_image_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrecipechoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrecipechoice',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='userrecipechoice',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userrecipefeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrecipefeedback',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='userrecipefeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='on_index',
            field=models.BooleanField(default=False, verbose_name='отображать на главной странице?'),
        ),
        migrations.AddField(
            model_name='userpage',
            name='disliked_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked', to='recipe_app.recipe', verbose_name='Непонравившиеся рецепты'),
        ),
        migrations.AddField(
            model_name='userpage',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked', to='recipe_app.recipe', verbose_name='Понравившиеся рецепты'),
        ),
        migrations.AddField(
            model_name='userpage',
            name='today_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.dailymenu', verbose_name='userpages'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, related_name='userpages', to='recipe_app.foodtag', verbose_name='Аллергии'),
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='UserRecipeChoice',
        ),
        migrations.DeleteModel(
            name='UserRecipeFeedback',
        ),
    ]
