# Generated by Django 5.2 on 2025-04-28 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_alter_subscription_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpage',
            name='menu_types',
        ),
        migrations.AddField(
            model_name='userpage',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='recipe_app.menutype', verbose_name='Тип меню'),
        ),
    ]
