# Generated by Django 5.2 on 2025-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_remove_shoppinglist_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='userpages', to='recipe_app.foodtag', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='disliked_recipes',
            field=models.ManyToManyField(blank=True, related_name='disliked', to='recipe_app.recipe', verbose_name='Непонравившиеся рецепты'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='liked_recipes',
            field=models.ManyToManyField(blank=True, related_name='liked', to='recipe_app.recipe', verbose_name='Понравившиеся рецепты'),
        ),
    ]
