# Generated by Django 5.2 on 2025-04-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_alter_userpage_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='today_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.dailymenu', verbose_name='Меню на сегодня'),
        ),
    ]
