# Generated by Django 5.2 on 2025-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_menutype_dailymenu_menu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.CharField(choices=[('mon', 'понедельник'), ('tue', 'вторник'), ('wen', 'среда'), ('thu', 'четверг'), ('fri', 'пятница'), ('sat', 'суббота'), ('sun', 'воскресенье')], default='mon', verbose_name='День недели'),
        ),
    ]
