# Generated by Django 5.2 on 2025-04-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_alter_dailymenu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to=settings.AUTH_USER_MODEL, verbose_name='Связанный аккаунт'),
        ),
    ]
