# Generated by Django 5.2 on 2025-04-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_alter_userpage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./menus/', verbose_name='Изображение меню'),
        ),
        migrations.AddField(
            model_name='userpage',
            name='menu_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe_app.menutype', verbose_name='Диета'),
        ),
    ]
