# Generated by Django 5.2 on 2025-04-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0014_menutype_image_userpage_menu_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpage',
            options={'ordering': ['username', 'user'], 'verbose_name': 'Страницы клиентов'},
        ),
        migrations.RenameField(
            model_name='userpage',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='last_name',
        ),
    ]
